### ISSUE TITLE
Errors deploying on Goerli

### ISSUE THREAD

**Issue by nfrgosselin** [allo-protocol/SeaGrants#103] opened 2023-12-18 18:58 UTC
When deploying a new pool to Goerli, the "Deploying new pool strategy" produces an error and gets stuck on "creating new pool" step

![image](https://github.com/allo-protocol/SeaGrants/assets/15041635/1e746c94-dff2-4994-85a5-eb7b653e8e4b)
![image](https://github.com/allo-protocol/SeaGrants/assets/15041635/fbb30514-e6e5-4f21-8a9f-7ba3d744bb7e)

**Comment by thelostone-mc** [comment] 2023-12-19 06:37
Duplicate of https://github.com/allo-protocol/allo-v2-spec/issues/52

**Closed by thelostone-mc** 2023-12-19 06:37 UTC
Labels: bug
